name: ci

on:
  pull_request:
    branches:
      - master

jobs:
  check_branch:
    runs-on: ubuntu-22.04
    container:
      image: homebrew/brew:3.5.2
      env:
        TAP_DIRECTORY: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps
    steps:
      - name: Retrieve package index
        run: |
          brew tap logisparte/beta-packages
          brew update

      - name: Check all package definitions
        run: |
          cd "$TAP_DIRECTORY/logisparte/homebrew-beta-packages" || exit 1
          git checkout "$GITHUB_HEAD_REF"
          for FORMULA_PATH in *.rb; do
            FORMULA="$(basename "$FORMULA_PATH" | cut -d "." -f 1)"
            brew cat "$FORMULA"
            brew install "$FORMULA"
            brew audit "$FORMULA"
            brew test "$FORMULA"
            brew uninstall "$FORMULA"
          done
